# Dependabot will run on day 6 of each month at 01:16 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "16 1 6 * *"
    open-pull-requests-limit: 15
    assignees:
      - "zechnerhubert"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "16 1 6 * *"
    open-pull-requests-limit: 15
    assignees:
      - "zechnerhubert"
